"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6yp0-&nch411(z)dd12__*mi_1wa-9m0%bxcg$i90x8lpqcb07'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp', # เพิ่มแอป myapp
    # เพิ่มแอปพลิเคชันของ django-allauth 
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # เปิดใช้งานระบบล็อกอินด้วย Google
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# เมื่อล็อกอินสำเร็จ หรือ ล็อกเอาต์ ให้เด้งกลับไปที่หน้าแรกสุด
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ตั้งค่าข้อมูลที่ต้องการดึงมาจากบัญชี Google
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}


# 1. ข้ามหน้ากดยืนยัน (Bypass intermediate page) ให้วิ่งไป Google ทันที
SOCIALACCOUNT_LOGIN_ON_GET = True

# 2. เพิ่มรายชื่ออีเมลของอาจารย์ หรือของคุณเองที่จะให้เป็นแอดมินระบบ
ADMIN_EMAILS = [
    'pleumzazazcz@gmail.com',  # เปลี่ยนเป็นอีเมล Google จริงของคุณ
    'test@gmail.com',      # สามารถเพิ่มได้หลายอีเมล โดยคั่นด้วยจุลภาค ( , )
]


# บอกให้ระบบดึงตัวคัดกรองสิทธิ์อีเมลมาใช้งาน
SOCIALACCOUNT_ADAPTER = 'myapp.adapters.CustomSocialAccountAdapter'

# 1. ข้ามหน้ากดยืนยันตอนออกจากระบบ ให้ทำงานทันทีเมื่อกดปุ่ม
ACCOUNT_LOGOUT_ON_GET = True

# 2. กำหนดว่าเมื่อออกจากระบบเสร็จแล้ว ให้เด้งกลับไปที่หน้าแรกสุดของเว็บ
LOGOUT_REDIRECT_URL = '/'

# บอก Django ว่าถ้าผู้ใช้ยังไม่ได้ล็อกอิน ให้ดีดไปที่ Google Login ทันที
LOGIN_URL = '/accounts/google/login/'

# 1. ปิดการยืนยันอีเมลทางกล่องข้อความ (สมัครปุ๊บใช้งานได้ปั๊บ)
ACCOUNT_EMAIL_VERIFICATION = 'none'

# 2. เปิดระบบสมัครสมาชิกอัตโนมัติจากข้อมูล Google (ไม่ต้องกรอกฟอร์มเพิ่มในครั้งแรก)
SOCIALACCOUNT_AUTO_SIGNUP = True