# Generated by Django 6.0.6 on 2026-06-15 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='คำค้นหา')),
                ('ai_result', models.TextField(blank=True, null=True, verbose_name='ผลวิเคราะห์จาก AI')),
                ('products_json', models.TextField(blank=True, default='[]', verbose_name='สินค้าดิบจาก Lazada')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันเวลาที่ค้นหา')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
