# Generated by Django 6.0.6 on 2026-07-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_items_json', models.TextField(verbose_name='ข้อมูลสินค้าที่เลือกเปรียบเทียบ (JSON)')),
                ('ai_recommendation', models.TextField(blank=True, null=True, verbose_name='คำแนะนำจาก AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='myapp.searchhistory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
